model: linear_svc
scale_data: True
weight_classes: True
split:
  test_size: 0.25
  random_state: 903

logistic:
  random_state: 903
  multi_class: multinomial

random_forest:
  random_state: 903
  n_estimators: 683
  max_features: sqrt
  max_depth: 30
  min_samples_split: 2
  min_samples_leaf: 2
  bootstrap: False

linear_svc:
  dual: False
  C: 1.0
  fit_intercept: True

gradient_boosting:
  random_state: 903

